[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[profile.default.fmt]
line_length = 100
tab_width = 4

[rpc_endpoints]
og_testnet = "${OG_RPC}"
adi_testnet = "${ADI_RPC}"
